runtime: nodejs14

env_variables:
    PORT: 3000
    REACT_APP_HOST: https://massive-rock-378707.wn.r.appspot.com/
    # REACT_APP_SERVER=https://massive-rock-378707.wn.r.appspot.com/
    REACT_APP_LOCATION_KEY: pk.b4e9da60b844ab669145dc3793610e06
    REACT_APP_WEATHER_KEY: 39c5906b0cef4dee9299c905f6bd8575
    REACT_APP_MOVIE_KEY: 7e9d4a67d59243cf1e078cd5e1c38ed0
instance_class: F1
automatic_scaling:
    min_idle_instances: 1
    max_idle_instances: automatic
    min_pending_latency: automatic
    max_pending_latency: automatic